# Generated by Django 5.2.13 on 2026-04-28 12:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='VIN')),
                ('brand', models.CharField(max_length=50, verbose_name='Marcă')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Număr înmatriculare')),
                ('capacity', models.IntegerField(verbose_name='Capacitate')),
                ('status', models.CharField(choices=[('active', 'Activ'), ('service', 'În service'), ('defective', 'Defect')], max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Autobuz',
                'verbose_name_plural': 'Autobuze',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nume')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Subiect')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data trimiterii')),
            ],
            options={
                'verbose_name': 'Mesaj Contact',
                'verbose_name_plural': 'Mesaje Contact',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Rută nespecificată', max_length=255, verbose_name='Nume Rută')),
                ('total_distance', models.FloatField(verbose_name='Distanță totală')),
                ('duration', models.DurationField(verbose_name='Durată estimată')),
            ],
            options={
                'verbose_name': 'Rută',
                'verbose_name_plural': 'Rute',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Denumire')),
                ('latitude', models.FloatField(verbose_name='Latitudine')),
                ('longitude', models.FloatField(verbose_name='Longitudine')),
            ],
            options={
                'verbose_name': 'Stație',
                'verbose_name_plural': 'Stații',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=150, verbose_name='Prenume')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nume')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefon')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresă')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilizator',
                'verbose_name_plural': 'Utilizatori',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnp', models.CharField(max_length=13, unique=True, verbose_name='CNP')),
                ('position', models.CharField(choices=[('driver', 'Șofer'), ('manager', 'Manager'), ('dispatcher', 'Dispecer')], max_length=20, verbose_name='Funcție')),
                ('hire_date', models.DateField(verbose_name='Data angajării')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salariu')),
                ('rating', models.FloatField(default=5.0, verbose_name='Rating')),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Număr permis')),
                ('status', models.CharField(choices=[('active', 'Activ'), ('medical_leave', 'Concediu medical'), ('vacation', 'Concediu de odihnă')], default='active', max_length=20, verbose_name='Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilizator')),
            ],
            options={
                'verbose_name': 'Angajat',
                'verbose_name_plural': 'Angajați',
            },
        ),
        migrations.CreateModel(
            name='RouteSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Luni'), (1, 'Marți'), (2, 'Miercuri'), (3, 'Joi'), (4, 'Vineri'), (5, 'Sâmbătă'), (6, 'Duminică')], verbose_name='Ziua săptămânii')),
                ('departure_time', models.TimeField(verbose_name='Ora plecare din prima stație')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.route')),
            ],
            options={
                'verbose_name': 'Orar Rută',
                'verbose_name_plural': 'Orare Rute',
                'unique_together': {('route', 'day_of_week', 'departure_time')},
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data cursei')),
                ('status', models.CharField(choices=[('scheduled', 'Programată'), ('active', 'În curs'), ('completed', 'Finalizată'), ('cancelled', 'Anulată')], default='scheduled', max_length=20, verbose_name='Status')),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='core.bus', verbose_name='Autobuz')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='core.employee', verbose_name='Șofer')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='core.routeschedule')),
            ],
            options={
                'verbose_name': 'Cursă',
                'verbose_name_plural': 'Curse',
                'unique_together': {('schedule', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(default='Nespecificat', max_length=255, verbose_name='Nume Pasager')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preț')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Data cumpărării')),
                ('is_boarded', models.BooleanField(default=False, verbose_name='Îmbarcat')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('end_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ending_tickets', to='core.station')),
                ('start_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starting_tickets', to='core.station')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.trip')),
            ],
            options={
                'verbose_name': 'Bilet',
                'verbose_name_plural': 'Bilete',
            },
        ),
        migrations.CreateModel(
            name='RouteStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Ordine')),
                ('time_from_start', models.DurationField(help_text='Durata de la începutul rutei până la această stație', verbose_name='Timp de la plecare')),
                ('distance_from_start', models.FloatField(default=0.0, help_text='Distanța în km de la începutul rutei până la această stație', verbose_name='Distanță de la plecare')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='core.route')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.station')),
            ],
            options={
                'verbose_name': 'Stație pe rută',
                'verbose_name_plural': 'Stații pe rută',
                'ordering': ['order'],
                'unique_together': {('route', 'order')},
            },
        ),
    ]
