# Generated by Django 5.2.12 on 2026-04-28 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestation',
            name='distance_from_start',
            field=models.FloatField(default=0.0, help_text='Distanța în km de la începutul rutei până la această stație', verbose_name='Distanță de la plecare'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='end_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ending_tickets', to='core.station'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='start_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starting_tickets', to='core.station'),
        ),
    ]
