# Generated by Django 5.2.12 on 2026-06-14 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('is_from_support', models.BooleanField(default=False, verbose_name='Este de la suport')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data trimiterii')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mesaj Chat',
                'verbose_name_plural': 'Mesaje Chat',
                'ordering': ['created_at'],
            },
        ),
    ]
