# Generated by Django 5.2.12 on 2026-06-16 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('merge_trips', 'Combinare curse'), ('bus_reallocation', 'Realocare autobuz'), ('driver_reallocation', 'Realocare șoferi')], max_length=32, verbose_name='Tip acțiune')),
                ('status', models.CharField(choices=[('applied', 'Aplicat'), ('rejected', 'Respins')], max_length=16, verbose_name='Status')),
                ('source', models.CharField(blank=True, max_length=64, verbose_name='Sursă plan')),
                ('model_name', models.CharField(blank=True, max_length=80, verbose_name='Model AI')),
                ('summary', models.CharField(max_length=255, verbose_name='Rezumat')),
                ('rationale', models.TextField(blank=True, verbose_name='Motivație')),
                ('plan_payload', models.JSONField(blank=True, default=dict, verbose_name='Plan')),
                ('related_trip_ids', models.JSONField(blank=True, default=list, verbose_name='Curse afectate')),
                ('error_message', models.TextField(blank=True, verbose_name='Eroare')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Aplicat de')),
            ],
            options={
                'verbose_name': 'Jurnal acțiune AI',
                'verbose_name_plural': 'Jurnal acțiuni AI',
                'ordering': ['-created_at'],
            },
        ),
    ]
