# Generated by Django 5.2.12 on 2026-04-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='buses/', verbose_name='Poză'),
        ),
    ]
