# Generated by Django 5.2.13 on 2026-04-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bus_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='image',
        ),
        migrations.AddField(
            model_name='ticket',
            name='passenger_name',
            field=models.CharField(default='Nespecificat', max_length=255, verbose_name='Nume Pasager'),
        ),
    ]
