# Generated by Django 5.2.13 on 2026-04-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_bus_image_ticket_passenger_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_boarded',
            field=models.BooleanField(default=False, verbose_name='Îmbarcat'),
        ),
    ]
